# These are supported funding model platforms

github: Aftab700 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Aftab700
open_collective: # Replace with a single Open Collective username
ko_fi: a # Replace with a single Ko-fi username
tidelift: a # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: a # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: a # Replace with a single Liberapay username
issuehunt: a # Replace with a single IssueHunt username
otechie: a # Replace with a single Otechie username
lfx_crowdfunding: a # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: a # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
